media:
  input: public/images
  output: /images

content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    format: md
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: slug
        label: Slug
        type: string

      - name: published
        label: Published Date
        type: date
        required: true

      - name: description
        label: Description
        type: string

      - name: category
        label: Category
        type: string

      - name: tags
        label: Tags
        type: list

      - name: image
        label: Cover Image
        type: image

      - name: author
        label: Author
        type: string
        default: "Javohir"

      - name: licenseName
        label: License
        type: string
        default: "CC BY-NC-SA 4.0"

      - name: pinned
        label: Pinned
        type: boolean
        default: false

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: body
        label: Body
        type: rich-text